### ISSUE TITLE
Yoinker crashing during Agent Select (Competitive)

### ISSUE THREAD

**Issue by drewkim1995** [isaacKenyon/VALORANT-rank-yoinker#66] opened 2022-06-03 08:55 UTC
[log-3.txt](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/8831044/log-3.txt)
[log-4.txt](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/8831045/log-4.txt)

Game keeps crashing during agent selects.

**Comment by D3CRYPT360** [comment] 2022-06-03 09:00
Does the program show any output on the screen?

**Comment by drewkim1995** [comment] 2022-06-03 09:25
![image](https://user-images.githubusercontent.com/52646640/171827702-e66f8f44-318e-4d37-b448-9831cf1da966.png)

**Comment by drewkim1995** [comment] 2022-06-03 09:25
Other times it just exits with no error message.

**Comment by paradox213** [comment] 2022-06-03 09:27
is this going to get fixed?

**Comment by deadly** [comment] 2022-06-03 19:06
It is crashing for me as well during agent select. Here is the error I am getting:
`  File "C:\Users\user\Desktop\VALORANT-rank-yoinker-1.252\main.py", line 200, in <module>
    loadouts = loadoutsClass.get_match_loadouts(pregame.get_pregame_match_id(), pregame_stats, "vandal", valoApiSkins, names,
  File "C:\Users\user\Desktop\VALORANT-rank-yoinker-1.252\src\Loadouts.py", line 40, in get_match_loadouts
    inv["Items"][weapon["uuid"].lower()]["Sockets"]["bcef87d6-209b-46c6-8b19-fbe40bd95abc"]["Item"][
TypeError: 'NoneType' object is not subscriptable`

**Comment by D3CRYPT360** [comment] 2022-06-03 19:11
Hello, we are aware of this issue, it seems like there is an issue with loadouts during agent select. 

Currently the only fix for this is to launch vRY after agent selection!

**Comment by D3CRYPT360** [comment] 2022-06-04 10:52
Hello, So far no luck. I believe this is a region related issue? Because all my EU accounts seems to work in agent select however all my AP accounts seems to fail. As a temporary "fix" until there is a way to figure the issue is to remove weapon loadout in agent select and show that data in game. Here is another temp build with that included. 
[vRY - TEMP FIX V2.zip](https://github.com/isaacKenyon/VALORANT-rank-yoinker/files/8837518/vRY.-.TEMP.FIX.V2.zip)

**Comment by isaacKenyon** [comment] 2022-06-05 16:54
This is fixed with release [1.26](https://github.com/isaacKenyon/VALORANT-rank-yoinker/releases/tag/1.26).

**Closed by isaacKenyon** 2022-06-05 16:54 UTC

**Comment by drewkim1995** [comment] 2022-06-06 08:57
Can confirm, 1.26 fixed this issue.
