### ISSUE TITLE
I am banned just from this app

### ISSUE THREAD

**Issue by KALITRIK** [isaacKenyon/VALORANT-rank-yoinker#76] opened 2022-06-28 18:05 UTC
i am banned
![valo ing](https://user-images.githubusercontent.com/70946597/176252310-d94ab073-8145-49bd-9bdb-4cef934fe443.PNG)

**Comment by isaacKenyon** [comment] 2022-06-28 18:14
Dupe of #73

**Closed by isaacKenyon** 2022-06-28 18:14 UTC
